apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-applicatio-deployment
  labels:
    app: node-application
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-application
  template:
    metadata:
      labels:
        app: node-application
    spec:
      containers:
      - name: node-application
        image: amfaa/backend-k8s:latest
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: node-application-service
spec:
  selector:
    app: node-application
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
