apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapp-deployment
  labels:
    app: nodeapp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodeapp-deployment
  template:
    metadata:
      labels:
        app: nodeapp-deployment
    spec:
      containers:
      - name: appserver
        image: amfaa/backend-k8s:latest
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: nodeapp-service
spec:
  selector:
    app: nodeapp-deployment 
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
